apache/cordova-windows

package.json
spec/e2e/endtoend.spec.js
spec/unit/MSBuildTools.spec.js
spec/unit/build.spec.js
spec/unit/fixtures/EmptyProject/AppPackages/CordovaApp.Phone_0.0.1.0_debug_Test/CordovaApp.Phone_0.0.1.0_AnyCPU_debug.appxbundle
spec/unit/fixtures/EmptyProject/AppPackages/CordovaApp.Windows80_0.0.1.0_anycpu_debug_Test/CordovaApp.Windows80_0.0.1.0_anycpu_debug.appx
spec/unit/package.spec.js
spec/unit/run.spec.js
template/cordova/lib/package.js

JIRA item: https://issues.apache.org/jira/browse/CB-8330

CB-8330 Added new unit tests

---

template/cordova/lib/prepare.js

[Corresponding JIRA issue](https://issues.apache.org/jira/browse/CB-8321)

CB-8321 Add supported orientations config.xml preference handling for `windows` platform

---

template/cordova/lib/prepare.js

This feature had already been done so I took the opportunity to clean up the
existing code.  There were multiple cases where the code scanned
multiple times (in worst case) for an element or set of elements,
for example.  This associates an XML namespace prefix with each
app manifest, so there's no need to map file name to Windows
platform version to prefix.  It's just in the data.

CB8673: Initial orientation settings

---

bin/check_reqs
bin/lib/check_reqs.js
bin/lib/create.js
spec/unit/check_reqs.spec.js

Implementation for https://issues.apache.org/jira/browse/CB-8954

CB-8954 Adds support for `requirements` command

---

cordova-js-src/platform.js
template/www/cordova.js

Creates channel for notifying when activationContext changes.

CB-8674 - activationContext

---

bin/lib/check_reqs.js

https://issues.apache.org/jira/browse/CB-9455

CB-9455 Fixed requirements check failure

---

template/cordova/lib/log.js
template/cordova/log
template/cordova/log.bat

https://issues.apache.org/jira/browse/CB-8936

CB-8936 Added logging functionality

---

template/cordova/lib/log.js

https://issues.apache.org/jira/browse/CB-8936
- Filter out logs from other applications
- Eliminated synchronous shelljs execution
- Minor formatting changes

CB-8936 Logs: Stability and formatting improvements

---

spec/unit/deployment.spec.js

https://issues.apache.org/jira/browse/CB-9632

CB-9632 Fixed tests not to fail on Travis-CI

---

template/cordova/lib/MSBuildTools.js

Fixes a small oversight in the previous pull request.

CB-9565 with logic tweak

---

template/cordova/lib/build.js

This PR fixes the issues from [CB-10303](https://issues.apache.org/jira/browse/CB-10303)

CB-10303 Fixes build arguments parsing

---

spec/unit/AppxManifest.spec.js
template/cordova/lib/AppxManifest.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10440)

CB-10440 Add CSS color names support for BackgroundColor on Windows

---

template/cordova/Api.js

This is in conjunction with vladimir-kotikov pull request/commit ac25c0f03380bb0640831a32ffa47c20df2b0126 to apply his changes to the cordova-windows version.

CB-10138 Adds missing plugin metadata to plugin_list module for Windows

---

template/cordova/lib/log.js

**Issue**
In the current system, the logs which are collected in the events must be listed in the CI logs is broken. For example, if there is a syntax error in one of the plugins, mobilespec(during testing) will crash the app. This information is available in event logs. This must be collected in the '[Gathering logs](https://ci.apache.org/builders/cordova-windows-store8.1/builds/1660/steps/gathering-logs/logs/stdio)' step and be available in CI logs. But, that is not happening and must be fixed.  
**Root Cause**
The issue is traced to 2 cause. 
1. **Query** 
The query format that was used to retrieve the event logs is incorrect. For example, even when the 'View Events Logs' tool reports the error, if you run the exact command in command line, it just returns empty results. This query …

CB-10640: Windows logging is broken

---

cordova-js-src/confighelper.js
template/www/cordova.js

Changes config.xml path to absolute
[Jira issue](https://issues.apache.org/jira/browse/CB-11150)

CB-11150 CI Error - Windows Platform - Could not find XHR config file

---

cordova-js-src/splashscreen.js
template/www/cordova.js

[Jira issue](https://issues.apache.org/jira/browse/CB-11156)

CB-11156 Change default FadeSplashScreenDuration value

---

spec/unit/MSBuildTools.spec.js
spec/unit/build.spec.js
template/cordova/lib/MSBuildTools.js
template/cordova/lib/build.js

CB-11548 windows: Respect user-specified msbuild location

---

template/www/cordova.js

See details in [CB-11522](https://issues.apache.org/jira/browse/CB-11522?focusedCommentId=15469653&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15469653)

CB-11522 [windows] Make cordova-js clone handle 'unknown' type

---

cordova-js-src/splashscreen.js
template/www/cordova.js

Windows
1. Fix splashscreen image path for ms-appx on Windows 10:
`<preference name="WindowsDefaultUriPrefix" value="ms-appx://" />`
2. Updated cordova-js to latest
Tested for CLI and platform scripts cases

CB-12044 Fix splashscreen image path for ms-appx on Windows

---

template/cordova/lib/AppxManifest.js

This brings support for Anniversary features such as https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/ etc.

Add support for uap3.

---

cordova-js-src/splashscreen.js

Windows
https://issues.apache.org/jira/browse/CB-12784
Fixes a crash described in the issue by by improving a check for supported functionality.
Ran on Windows 10 Creators Update (build 15063.250), Ran on Windows 8.1, Ran on Windows 10 mobile

CB-12784 Fixed a crash on Windows 10 Creators Update

---

appveyor.yml

CB-13877 more env information about msbuild and visual studio on appveyor

---

appveyor.yml

See https://issues.apache.org/jira/browse/CB-13889

CB-13889 Allow test failures for Visual Studio 2017 environments

---

template/cordova/lib/prepare.js

Quick fix for GH-299 (#299)
It is recommended to merge this by squash since the actual commit message is not properly descriptive.
closes #299

Workaround for unknown splashscreen

---

template/cordova/lib/build.js

fix: Better build error

---

template/cordova/lib/build.js

fix: fail on no build config / msbuild to build

---

README.md

UPDATED: replace existing requirements with link, according to the current situation

Requirements link in README.md

---

bin/check_all
bin/check_reqs
bin/create
bin/update
cordova-js-src/.eslintrc.yml
cordova-js-src/confighelper.js
cordova-js-src/exec.js
cordova-js-src/platform.js
cordova-js-src/splashscreen.js
package.json
template/cordova/build
template/cordova/clean
template/cordova/log
template/cordova/prepare
template/cordova/run
template/cordova/version

- Ensure to lint as many files as possible
- Binaries w/out file extension and `cordova-js-src/*` hadn't been linted before
- Apply fixes where necessary

Lint everything

---

package.json

Bump testing dependencies to latest version.
- jasmine@^3.5.0
- nyc@^15.0.1
- rewire@^5.0.0
Requires: #376
- `npm run cover`

feat: bump testing dependencies to latest version

---

.travis.yml
appveyor.yml

* Test with Node 14.x
* Added Node 14.x CI all workflow configurations.
See https://github.com/apache/cordova/issues/223 for more details.
* No local testing required.
* Use CI service test results

ci: add node-14.x to workflow
