cordova-js-src/exec.js

Due to the enumeration of cordova.callbackStatus (NO_RESULT = 0 and OK = 1), the logic used for defaulting to cordova.callbackStatus.OK will always default to cordova.callbackStatus.OK when the callbackStatus is set to cordova.callbackStatus.NO_RESULT.
This change addresses this issue by first checking if callbackOptions.status is null and defaulting to cordova.callbackStatus.OK, otherwise it will accept the callbackOptions.status value provided by the user.

Fix for callback invocation with NO_RESULT

---

cordova-windows10.md
template/cordova/lib/ConfigParser.js

Feedback was negative for the change from windows-target-version to WindowsTargetVersion.  Opportunistically changing it back before it becomes a thing.

Reverted change to version which added pascal casing based on CR feedback

---

bin/lib/create.js
template/cordova/lib/package.js
template/cordova/lib/prepare.js
template/package.phone.appxmanifest
template/package.windows.appxmanifest
template/package.windows80.appxmanifest

We should NOT change Application/Id in .appxmanifest according to widget/id (config.xml) as it does not make any sense, but could lead to build failures like in this particular case:
https://issues.apache.org/jira/browse/CB-8856

CB-8856 Fix 'Id' attr is invalid when creating Windows Store submission build

---

template/cordova/lib/prepare.js

Added the "WindowsToastCapable" preference to indicate that the app can support toasts.  This is to support the Local Notifications plugin.  See https://issues.apache.org/jira/browse/CB-8946

CB-8946: Added the "WindowsToastCapable" preference 

---

template/CordovaApp.Phone.jsproj
template/CordovaApp.Windows.jsproj
template/CordovaApp.Windows10.jsproj
template/CordovaApp.Windows80.jsproj
template/CordovaApp.shproj
template/CordovaApp.sln

Currently in dev12 solution we're using shared project. The shared project has some logic that doesn't work with windows10 projects. (This is due to version changes we have from 8, 8.1 to 10.X.Y.Z)
It looks like the best option we have is to seperate out win10 to a new solution.

CB-9045 Create a new solution for Win10/Dev15

---

template/cordova/lib/MSBuildTools.js
template/cordova/lib/prepare.js

Removes isTargetingWin10 logic and fails silently in case system does not have UAP tools installed.

CB-9059 removed targetingWin10 logic from prepare

---

template/cordova/version.bat

This fixes [CB-9073](https://issues.apache.org/jira/browse/CB-9073)

CB-9073 Fixes build error when path to project contains `&` symbol

---

template/cordova/lib/run.js

`cordova run` will fail for windows if invoked from admin prompt. Currently we will wait until ActivateApplication stage and fail afterwards. We should fail fast and improve user experience.

CB-9097 fail with a more descriptive error if run as admin

---

template/cordova/lib/run.js

Windows 10 Phone emulator is currently not supported but deployment from VS is possible.
We should tell users to use VS instead, until this issue is resolved.

CB-9164 Better error message when deploying to Windows10 phone emulator

---

template/cordova/lib/deployment.js
template/cordova/lib/package.js

AppDeployCmd also failed to install an app when:
- The emulator had been off previously
- It had been started with the AppDeployCmd /uninstall command
- The next command was to then install an app
This change detects the condition (only for emulator targets) and retries
once.  This appears to correct the issue.

CB-9482: Upon further investigation of CI failures, we saw that

---

template/cordova/lib/MSBuildTools.js

This error is a result of using x64 Node and an incompatibility with x64 msbuild; the .NET Native compiler is x86 only (for where it can run).  As a result, when msbuild-x64 tries to use it, it fails.  This works around the issue by running x86 instead.

CB-9565: Build failure for Windows 10.  This error is a result of using

---

template/cordova/lib/MSBuildTools.js
template/cordova/lib/build.js

Reference the JIRA issue for more explanation.
The targets filter for 15.0 is currently the same as 14.0, but I copied to a separate function for clarity and in case it ever changes while 15.0 is being developed further.

CB-10292: Windows platform support for next version of VS/MSBuild

---

spec/unit/build.spec.js
template/cordova/lib/build.js
template/cordova/lib/prepare.js

This PR moves adding BOM to JS files from prepare to build stage. This should fix the potential problem (as explained in [mailing list discussion](http://markmail.org/thread/cg5s2jvxvyyqcqpd)) when www files already contain BOM signatures at the time when 'after_prepare' hook ([or simulated 'pre_package' hook](https://github.com/apache/cordova-lib/commit/4478eaf0783a2f73962e5911a0c26cc4db1da241)) is fired.
JIRA issue: [CB-10193](https://issues.apache.org/jira/browse/CB-10193)

CB-10193 Add BOM to www files at build stage instead of prepare

---

template/cordova/lib/PluginHandler.js

I fixed a simple bug that caused an exception EISDIR when removing a plugin that includes a <frame> tag.
PluginHandler.js should have passed the project file instead of the plugin directory.

CB-10381 fix the bug when removing a plugin with a <framework> tag

---

spec/unit/AppxManifest.spec.js
spec/unit/JsprojManager.spec.js
template/cordova/lib/AppxManifest.js
template/cordova/lib/JsprojManager.js

This fixes [CB-10394](https://issues.apache.org/jira/browse/CB-10394)

CB-10394 Do not cache manifest file while getting package name

---

spec/unit/Prepare.Win10.spec.js
template/cordova/lib/prepare.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10446)

CB-10446 Windows 10 Cordova Application restart instead of resume

---

template/cordova/lib/build.js

If "ARM" is passed to --archs, the Appx file is compiled, but the build
will fail due to a case sensitive string comparison.

CB-10714 Ignore case for --archs

---

spec/unit/ConfigChanges.spec.js
template/cordova/Api.js
template/cordova/lib/ConfigChanges.js

This fixes a problem when some of capabilities, added by plugin are being modified at 'prepare' stage due to special Windows logic and then aren't removed when uninstalling plugin. For details see [CB-11066](https://issues.apache.org/jira/browse/CB-11066)

CB-11066 Remove uap prefixed capabilities when plugin has added regular ones

---

spec/unit/build.spec.js
template/cordova/lib/build.js
template/cordova/lib/prepare.js

This PR reverts changes, made in #134
The reason of reverting is that original change causes the problems with submitting apps to Windows store when app is built using Visual Studio, because BOM signatures were being added by cordova-windows in `build.js`. In this PR processing `www` is moved back to prepare, and hence all `www` assets will be properly updated to have BOM when the project is opened in VS.
For more background see JIRA issue [CB-11241](https://issues.apache.org/jira/browse/CB-11241)

CB-11241 Return adding BOM to www back to prepare

---

spec/unit/pluginHandler/windows.spec.js
template/cordova/lib/JsprojManager.js
template/cordova/lib/PluginHandler.js

The issue was that we have been passing a relative path during `JsprojManager`.`addProjectReference` and an absolute path during `JsprojManager`.`removeProjectReference` so that regexp failed to find and remove it.
The tests were passing as they were also using absolute paths to the dummy plugin (it was not being added to the test project at all).
Initial idea was to use relative paths instead for project sharing: [CB-10927 Framework references in plugin.xml file prevent Windows Universal projects from being used on other machines](https://issues.apache.org/jira/browse/CB-10927)
Also updated the tests to use relative paths to the ProjectReferences.
[Jira issue](https://issues.apache.org/jira/browse/CB-11558)

CB-11558 Make windows plugin rm remove ProjectReference items

---

spec/unit/run.spec.js
template/cordova/lib/run.js

This PR aligns arguments parsing logic with `build` command where passing `--archs` either as CLI argument (`cordova build --archs`) or platform arg, behind `--` (`cordova build -- --archs`) doesn't make any difference.
See also original issue: [CB-11478](https://issues.apache.org/jira/browse/CB-11478)

CB-11478 Parse --archs option consistently

---

template/cordova/Api.js
template/cordova/lib/prepare.js

JIRA [CB-11657](https://issues.apache.org/jira/browse/CB-11657)
This PR addresses WACK validation issues when app has been built from VS after installing/restoring plugins. In this case some files, added by plugins would not have BOM

CB-11657 Add bom to www after plugin operations

---

template/CordovaApp.Phone.jsproj
template/CordovaApp.Windows.jsproj
template/CordovaApp.Windows10.jsproj
template/cordova/prebuild-10.js
template/cordova/prebuild-81.js
template/cordova/prebuild-phone-81.js
template/cordova/prebuild.js

Patch start page to include base.js reference to HTML as a workaround
[Jira issue](https://issues.apache.org/jira/browse/CB-11658)

CB-11658 activated event is not fired on Windows 10 RS1

---

bin/lib/check_reqs.js

This is a fix for https://issues.apache.org/jira/browse/CB-11857
Just fixed the invalid use of `Array.prototype.splice()` method.

CB-11857 Fixed VS 2015 detection on Windows 10 Anniversary

---

template/cordova/Api.js

windows
catches possible error
jshint

CB-11999 platformAPIs contain js code that is deceptively uncallable

---

bin/lib/create.js

Fixes missing `base.js` in `www` folder when project is created without Cordova CLI
- [-] Added automated test coverage as appropriate for this change.

CB-12042 Copy base.js to www directory in 'create'

---

spec/unit/pluginHandler/windows.spec.js
template/cordova/lib/JsprojManager.js

Windows
The real issue in CB-11825 was in a wrong plugin configuration - resource-file.target (Content.Link) should use backslashes (reverted from commit 1417b932c836c0fe21cca902e5098fa12e98fe82)
Run platform autotests, created and run helloworld project

CB-12071 Fix for CB-11825 breaks usage of InProcessServer in Cordova Windows

---

spec/unit/ConfigChanges.spec.js
spec/unit/fixtures/org.test.plugins.capabilityplugin/plugin.xml
template/cordova/lib/ConfigChanges.js

This PR makes available to use device capabilities in package.windows10.appxmanifest.
Auto test

CB-12124: Make available device capabilities in package.windows10.appxmanifest

---

cordova-js-src/splashscreen.js
template/www/cordova.js

[Jira issue](https://issues.apache.org/jira/browse/CB-11751)
Replaced element implicit calls by id to variable usage.
Don't fade out if splash element has been removed.
Manual and auto tests

CB-11751 'extendedSplashScreen' is undefined

---

cordova-js-src/platform.js
template/www/cordova.js

Windows
Don't subscribe to WinRT lifecycle events if Cordova is running in webview.
Also made confighelper to load after WinJS as it depends on it.
[CB-12193](https://issues.apache.org/jira/browse/CB-12193)
Manual tests.

CB-12193 cordova.js crashes windows app if there is no CoreWindow

---

spec/unit/build.spec.js
template/cordova/build
template/cordova/lib/MSBuildTools.js
template/cordova/lib/build.js

This PR adds `buildFlag` CLI argument and corresponding option for `build.json` file (similar to iOS) to allow users to pass arbitrary options directly to MSBuild
Added new tests, ran unit and e2e tests

CB-12239 Add buildFlag option similar to iOS

---

cordova-js-src/splashscreen.js
template/www/cordova.js
template/www/css/splashscreen.css

Windows
Fixes splash jump bug (affected mostly Windows 10 Mobile devices, especially with soft navigation bar)
Manual testing

CB-11177 SplashScreen gets shifted on Windows devices with soft navbar

---

cordova-js-src/splashscreen.js
template/www/cordova.js

Windows
Colorize titlebar to match splash background color
Manual testing

CB-12238 [Windows] Colorize titlebar to match splash bg color

---

spec/e2e/endtoend.spec.js
template/cordova/lib/build.js

Windows
Adds a MSBuild flag to get appxupload generated for Windows 10 release builds.
Auto and manual tests

CB-12298 [Windows] bundle.appxupload not generated for Windows 10 target

---

template/cordova/prebuild.js

Windows
Continue the build if the start page is missing on disk.
Run npm test, manual test

CB-12415 Windows build fails if start page is missing

---

.gitignore
package.json
spec/e2e/endtoend.spec.js
spec/support/jasmine.json
spec/unit/AppxManifest.spec.js
spec/unit/ConfigChanges.spec.js
spec/unit/JsprojManager.spec.js
spec/unit/MSBuildTools.spec.js
spec/unit/Prepare.Win10.spec.js
spec/unit/Version.spec.js
spec/unit/WindowsConfigParser.spec.js
spec/unit/build.spec.js
spec/unit/check_reqs.spec.js
spec/unit/clean.spec.js
spec/unit/deployment.spec.js
spec/unit/pluginHandler/common.spec.js
spec/unit/pluginHandler/windows.spec.js
spec/unit/run.spec.js
template/cordova/lib/PluginInfo.js

CB-12018 : updated tests to work with jasmine instead of jasmine-node
Uses jasmine to test instead of jasmine-node.

CB-12018 : updated tests to work with jasmine instead of jasmine-node

---

README.md
node_modules/cordova-registry-mapper/README.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

bin/lib/check_reqs.js
template/cordova/lib/MSBuildTools.js

this one!
Teaches `cordova-windows` to properly recognize VS 2017 installation in the system.
`cordova requirements` on Windows 10 / Windows 8.1 with only VS 2017, as well as with other VS versions.

Cb 12636 Fix check_reqs to properly find VS 2017

---

template/cordova/lib/ConfigParser.js

This addresses an issue when app developers only have VS-2017 which does not include the older tooling.
UWP 'should' be the default going forward anyway.

CB-13237 Default to UAP

---

template/cordova/lib/package.js

Windows
Fix a typo in an error message during build
none (only a string has been changed, and none of the tests expects a specific error message wording
- [ X ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ X ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.

CB-13422: (windows) Fix typo in build error message

---

cordova-js-src/splashscreen.js
template/www/cordova.js

windows
adds support for transparent splash screen background color.
built app with forked/updated repository and manually tested splash screen background color with RGB and 'transparent' values.

CB-13641: (windows) support transparent splash screen background color.

---

spec/e2e/endtoend.spec.js
template/cordova/lib/MSBuildTools.js
template/cordova/lib/build.js
template/cordova/prebuild.js

Windows 10, Visual Studio 2015 and 2017
This PR fixes the e2e tests that were broken since https://issues.apache.org/jira/browse/CB-13237 was merged which was not caught because of broken CI.
For that I rewrote all of them from "default 8.1" to "default 10" by fixing the `expect`s, extracting the comparison stuff in its own function along the way. I think I replicated all test cases that were there before.
Local runs of e2e test suite + CI.
Note: The remaining 1 failing test with Visual Studio 2017 is from another, unrelated change (that was also not caught because of broken CI). I changed the order of tests so it is the last one being executed, so all the others are passing. This one will be tackled in https://issues.apache.org/jira/browse/CB-13834

CB-13829 Fix tests that were broken since CB-13237

---

template/cordova/lib/ConfigParser.js

... which means the same but works for check_reqs as well.
This is an "update" to https://github.com/apache/cordova-windows/pull/241
Manual installation as platform and ran `cordova requirements` successfully:
```
C:\Projects
λ cd "Cordova Projects\
C:\Projects\Cordova Projects
λ cordova create windowsMaster2
Creating a new cordova project.
C:\Projects\Cordova Projects
λ cd windowsMaster2
C:\Projects\Cordova Projects\windowsMaster2  (helloworld@1.0.0)
λ cordova platform add https://github.com/apache/cordova-windows#master
Using cordova-fetch for https://github.com/apache/cordova-windows#master
Warning: using prerelease platform windows@5.1.0-dev.
Use 'cordova platform add windows@latest' to add the latest published version instead.
Adding windows project...
Creating Cordova Windows …
```

CB-13870 change default from UAP to 10.0 

---

spec/e2e/endtoend.spec.js
spec/unit/build.spec.js
template/cordova/build
template/cordova/lib/build.js
template/cordova/run

https://issues.apache.org/jira/browse/CB-13817
Adds `uwp` as an alias for `uap` to the `--appx` param so one can also use it to trigger a Win10 build.
Locally + CI.

CB-13817 Add new alias `uwp` for `--appx` param including tests

---

spec/e2e/endtoend.spec.js
template/config.xml
template/cordova/prepare
template/cordova/prepare.bat

… to prepare project files
(based on `clean` and some terrible code to build a `project` object)
also adds default `config.xml` as in other projects
replaces #250

CB-13875 add `prepare` script that can be called in e2e tests

---

template/cordova/lib/MSBuildTools.js
template/cordova/lib/build.js

This PR takes first steps to improbe the MSBuildTools selection:
- Output the path of the use MSBuildTools during build
- move misplaced method from build.js
- Add some comments to make clearer where methods are used

CB-13877 First MSBuildTools.js work: Debug output, move misplaced method, comments

---

bin/check_all
bin/check_all.bat
bin/lib/check_reqs.js

- New command line script `check_all` that does the same thing as `cordova requirements windows`
- Fix check_reqs to work again (by pinning it to 10.0)

CB-13870 Improve check_reqs

---

spec/unit/build.spec.js
template/cordova/lib/MSBuildTools.js
template/cordova/lib/build.js

This PR cleans up MSBuildTools.js. After this change it contains all the functionality regarding MSBuildTools selection. The order of functions is optimized, lots of comments and `console.log` statements are added.
Unfortunately 3 of the existing tests do not work any more after these changes and I could not figure out how to fix them. Help would be greatly appreciated.

CB-13877 Clean up MSBuildTools.js

---

template/cordova/lib/MSBuildTools.js

Adds support for VS2017 (15.5) during the MSBuild selection

CB-13883 Visual Studio 2017 support 

---

appveyor.yml
spec/unit/build.spec.js
template/cordova/lib/MSBuildTools.js

Adds a MSBUILDDIR env var to influence the MSBuildTools selection process by providing a direct path to it.

CB-13878 MSBUILDDIR env variable

---

package.json

Windows
- pin some more bundled dependencies to clear the red highlights in `npm outdated --depth=0`
- `npm audit` with npm@6.1.0 (latest version) shows 0 vulnerabilities
- able to build and run new Cordova project with `brodybits/cordova-windows#cb-14145-pin-some-more-bundled-deps-in-patch-only` platform version on the following Node.js versions
- deprecated Node.js 4 (npm 2.15.11)
- Node.js 8 (npm 5.6.0)
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

CB-14145 pin some more bundled deps in 6.0.x patch only

---

template/Properties/Default.rd.xml

<https://issues.apache.org/jira/browse/CB-14224>
Windows
Proposed `template/Properties/Default.rd.xml` updates in 6.0.x patch release, as rebased & squashed from #284:
- add MIT license text from <https://github.com/Microsoft/Windows-universal-samples>, with left aligment fixed
- add link to <https://github.com/Microsoft/Windows-universal-samples/blob/master/SharedContent/cs/Default.rd.xml>
As I said in #284 I think this is desired to satisfy the Apache RAT tool (used by `coho audit-license-headers`). Alternative may be to add an exception for this file but I think it would be better to follow the standard Apache procedure if possible.
I verified that `coho audit-license-headers -r windows` with these changes does not show the missing license header any more.
- ~~Added automated test …

CB-14224 Default.rd.xml updates (6.0.x patch)

---

template/Properties/Default.rd.xml

<https://issues.apache.org/jira/browse/CB-14224>
Windows
`template/Properties/Default.rd.xml` header fixes:
- add MIT license text from <https://github.com/Microsoft/Windows-universal-samples>, with left aligment fixed
- add link to <https://github.com/Microsoft/Windows-universal-samples/blob/master/SharedContent/cs/Default.rd.xml>
Rationale: I think it is desired to add license headers whenever possible to satisfy Apache RAT license auditing tool. While I think it should be possible to configure the auditing tool to skip this file I would rather follow the practice of adding the license text whenever possible.
NOTE: I also proposed updates to LICENSE text in <https://github.com/Microsoft/Windows-universal-samples/pull/949> _(not included in this PR)_.
I verified that `coho …

CB-14224 Default.rd.xml header fixes

---

.travis.yml
appveyor.yml
package.json

windows
- Drops Node 4 support from Travis CI and AppVeyor.
- Adds Node 8 and 10 to Travis CI.
- Adds node node engine requirement flag to package.json
**Travis CI**
- https://travis-ci.org/erisu/cordova-windows/builds/411112975
**AppVeyor**
- https://ci.appveyor.com/project/erisu/cordova-windows/build/1.0.2

CB-14075: (windows) Remove Node 4 from CI - cordova-windows

---

template/Properties/Default.rd.xml

<https://issues.apache.org/jira/browse/CB-14225>
Windows
- Fix sample Namespace Serialize attribute in `template/Properties/Default.rd.xml`, according to `Default.rd.xml` in C# UWP project generated by Visual Studio 2017
I also raised <https://github.com/Microsoft/Windows-universal-samples/pull/950> to apply a similar fix there.
Also related:
- #284 - fix license text & add link to `template/Properties/Default.rd.xml` (as reported in <https://issues.apache.org/jira/browse/CB-14224>)
- <https://github.com/Microsoft/Windows-universal-samples/pull/949> - fix license txt (related to but not part of #284)
- Visual inspection
- check diff
- ~~Added automated test coverage as appropriate for this change.~~

CB-14225 fix sample Namespace Serialize attribute in template/Properties/Default.rd.xml

---

.gitignore
package.json
spec/e2e/endtoend.spec.js
template/cordova/prepare

windows
Fixing following spec error
```
C:\Users\knaito\Documents\work\cordova-develop\cordova-windows\testcreate 応用\cordova\node_modules\fs-extra\lib\copy-sync\copy-sync.js:185   
throw new Error('Source and destination must not be the same.')                                                                         
Error: Source and destination must not be the same.
``` 
The above error happens because `FileUpdater` in `cordova-common` checks args strictly. (The older `cordova-common`, does not check args strictly)
Therefore this PR updates tests' directory structure in order to statisfy the correct args.
Detecting `config.xml` in `cordova/prepare` is also improved accroding to the new tests' directory structure.
```
npm run test
```

change temporary directories for tests

---

appveyor.yml
spec/e2e/endtoend.spec.js

The CI tests on AppVeyor using VS 2017 were allowed to fail completely because of _one_ E2E test that is broken under these conditions. This is confusing and could mask any other broken tests.
Example: https://ci.appveyor.com/project/ApacheSoftwareFoundation/cordova-windows/builds/23755792
Instead of allowing the whole suite to fail when using VS 2017, we only skip the known-bad tests when VS 2017 on AppVeyor is used.

Conditionally skip the _one_ broken test for VS 2017 instead of allowing the whole suite to fail

---

bin/lib/create.js

Fixes #326
Properly resolve the path to our dependency instead of guessing it.
**Manual**:
```sh
$ cordova create cordovaWindows7Test
Creating a new cordova project.
$ cd cordovaWindows7Test
$ cordova platform add ~/code/cordova-windows
Warning: using prerelease platform windows@7.1.0-dev.
Use 'cordova platform add windows@latest' to add the latest published version instead.
Adding windows project...
Creating Cordova Windows Project:
Path: platforms/windows
Namespace: io.cordova.hellocordova
Name: HelloCordova
Windows project created with cordova-windows@7.1.0-dev
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for windows
Adding …
```

Fix path to winjs dependency

---

template/cordova/lib/MSBuildTools.js

Latest Visual Studio 2017 comes with MSBuild 15.9:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
λ msbuild -version -nologo
15.9.21.664
```
As we have a strangely hardcoded list of support MSBuild versions, this needs to be added to work.

Support latest Visual Studio 2017 (15.9.x)

---

appveyor.yml
spec/e2e/endtoend.spec.js

This PR splits the tests into two blocks, one for Windows 10 and one for Windows 8.1. The 8.1 block has a `beforeEach` that calls `pending` for each test if they run on the VS17 image (and `MSBUILDDIR` is not manually overridden to use MSBuildTools 14 [from VS15]).
Also adds another environment where `MSBUILDDIR` is explicitly set to 15 to detect regressions when the system image changes.
closes #334

refactor: split tests into suites for Windows 10 and Windows 8.1 (to be able to disable conditionally)

---

package.json

- cordova-common@^3.2.0 update in dependencies - to ensure that the recent cordova-common update, with the recent fs-extra@8 update, will be installed even when the user would upgrade from cordova-windows@7.0.0 using npm
- fs-extra@8 update in devDependencies
- nyc@14 update in devDependencies - resolves a non-production npm audit issue
AppVeyor CI build is green for these changes on my fork.
I would normally have proposed these changes in separate PRs, don’t have so much time to do this right now. If approved, I think a merge commit should be used to merge these changes into `master`.
I hope we can get these changes reviewed, approved, and merged before we make the cordova-windows@7.1.0 release.

Dependency updates July 2019

---

.travis.yml
appveyor.yml
package.json

Bump node engine requirement to >=10.0.0

breaking: bump node support >=10.0.0

---

package.json

- Upgrade `fs-extra` dependency to use latest
- `fs-extra` should be a release dependency, not a dev dependency
Requires: #376
- `npm run cover`

chore: upgrade & set fs-extra as release dependency
